name: pdf_manager
description: A new Flutter project.

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none'

# Version number for the application
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  pdf: ^3.8.2
  syncfusion_flutter_pdf: ^27.2.3
  file_picker: ^8.1.4
  pdf_compressor: ^0.2.0
  after_layout: ^1.2.0
  share_plus: ^10.1.2
  flutter_launcher_icons: ^0.14.1
  font_awesome_flutter: ^10.5.1
  cupertino_icons: ^1.0.2
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application
  assets:
    - assets/app_icon.png

  # Uncomment if you need to add custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
